# "name" is short hand of "COMPOSE_PROJECT_NAME" when defined. But you must use correct name, is "COMPOSE_PROJECT_NAME"
name: game_stairgun
services:
  # client:
  #   extends:
  #     file: ../../Phaser/Game_StairGun__Client_Phaser/docker-compose.yaml
  #     service: client
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - stairgun_game:/data/db
    networks:
      game_stairgun:
  server:
    image: kyuseishu/${COMPOSE_PROJECT_NAME}/server
    container_name: server
    ports:
      - 4000:4000
    build:
      dockerfile: dockerfile
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongodb:27017/stair_gun_game
      - MIGRATE_MONGO_URI=mongodb://mongodb:27017/stair_gun_game
      - ALLOWED_ORIGINS="['http://localhost:3000', 'http://127.0.0.1:3000', 'http://localhost:5500', 'http://127.0.0.1:5500', 'https://localhost:5500']"
    networks:
      game_stairgun:

volumes:
  stairgun_game:
    name: ${COMPOSE_PROJECT_NAME}

networks:
  game_stairgun:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge
