export { default as ICard } from './ICard'
export { default as IItem } from './IItem'
export { default as IMap } from './IMap'
export { default as IObject } from './IObject'
export { default as IPlayer } from './IPlayer'
